default_platform(:ios)

platform :ios do
  desc "✅ Run tests"
  lane :tests do
    scan(
      project: "Rick&Morty.xcodeproj",
      scheme: "Rick&Morty",
      only_testing: "Rick&MortyTests",
      device: "iPhone 15 Pro",
      code_coverage: true,
      clean: true,
      skip_build: false,
    )
  end
end
